# Generated by Django 3.0 on 2021-06-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuja', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
